import { useEffect, useMemo, useRef, useState } from 'react';
import { SparklesIcon, ExclamationTriangleIcon, XCircleIcon, XMarkIcon } from '@heroicons/react/24/outline';
import type { SpecData } from '../../types';
import type { DraftEnvelope } from '../../hooks/useSpecDrafts';
import { specJson } from '../../data/spec';
import {
  COLOR_HEX_MAP,
  SHAPE_LABELS_SHORT_JA,
  POSITION_LABELS_JA,
} from '../../utils/specHelpers';
import { evaluateNgRules } from '../../utils/ngRules';
import { useToast } from '../Toast';
import { useStep2Proposals } from '../../hooks/useStep2Proposals';
import ProposalDeck from './ProposalDeck';
import BaselineBadge from './FieldWithBaseline';
import { applyProposal, diffFromProposal } from './applyProposal';

interface Props {
  data: SpecData;
  updateData: (data: Partial<SpecData>) => void;
  onNext: () => void;
  onBack: () => void;
  /** Used by the Route B guide banner to show the source draft's productCode. */
  draftLookup?: (id: string) => DraftEnvelope | null;
  /** Tab-nav callback wired from App.tsx's `goStep`. Used by the
   *  position-missing fallback banner to send the user back to Step1. */
  onStepChange?: (step: 1 | 2 | 3 | 4) => void;
}

function PositionMissingBanner({ onStepChange }: { onStepChange?: (step: 1 | 2 | 3 | 4) => void }) {
  return (
    <div
      role="alert"
      className="bg-amber-50 border border-amber-200 rounded-md p-4 mb-4"
    >
      <div className="flex items-start gap-3">
        <div className="flex-1">
          <div className="text-sm font-medium text-amber-900 mb-1">
            ポジションが未設定です
          </div>
          <div className="text-sm text-amber-800">
            ラグジュアリー / スタンダード / カジュアルのいずれかを STEP1 で選択してください。
          </div>
        </div>
        {onStepChange && (
          <button
            type="button"
            onClick={() => onStepChange(1)}
            className="flex-shrink-0 inline-flex items-center justify-center px-4 py-2 bg-amber-600 text-white text-sm font-medium rounded-md hover:bg-amber-700 transition-colors min-h-[44px]"
          >
            STEP1 に戻る
          </button>
        )}
      </div>
    </div>
  );
}

function GuideBanner({
  data,
  draftLookup,
  onClose,
}: {
  data: SpecData;
  draftLookup?: Props['draftLookup'];
  onClose: () => void;
}) {
  let title: string;
  let message: string;
  if (data.originRoute === 'A') {
    title = `サンプル「${data.originSampleId ?? '(不明)'}」を起点にしています`;
    message = '下記の提案から1つを選んで「適用」を押してください。';
  } else if (data.originRoute === 'B') {
    const source = data.originDraftId && draftLookup ? draftLookup(data.originDraftId) : null;
    const label = source?.productCode || data.originDraftId || '(不明)';
    title = `ドラフト「${label}」を複製しています`;
    message = '必要な項目を編集してください。提案は手動で生成できます。';
  } else {
    return null;
  }
  return (
    <div className="bg-blue-50 border border-blue-200 rounded-md p-3 mb-4 flex items-start justify-between gap-2">
      <div className="flex-1 min-w-0">
        <div className="text-sm text-blue-900 font-medium mb-1">{title}</div>
        <div className="text-sm text-blue-700">{message}</div>
      </div>
      <button
        type="button"
        onClick={onClose}
        aria-label="ガイドを閉じる"
        className="flex items-center justify-center w-11 h-11 -mt-1 -mr-1 text-blue-400 hover:text-blue-600 flex-shrink-0"
      >
        <XMarkIcon className="w-5 h-5" />
      </button>
    </div>
  );
}

export default function Step2({ data, updateData, onNext, onBack, draftLookup, onStepChange }: Props) {
  const { showToast, ToastView } = useToast();
  const baseline = data.baseProposal ?? null;
  const [showGuide, setShowGuide] = useState(true);
  const autoGeneratedRef = useRef(false);
  const isPositionMissing = !data.position || data.position.trim() === '';

  const {
    proposals,
    currentProposalIndex,
    setCurrentProposalIndex,
    generateProposals,
    regenerateProposals,
    getProposalWarnings,
  } = useStep2Proposals(data, {
    onNoBaseAutoFill: () => showToast('推奨データが見つかりませんでした', 'error'),
    onRegenerated: () => showToast('再生成しました'),
    onRegenerateFailed: () => showToast('新しいパターンを生成できませんでした', 'error'),
  });

  const handleApplyProposal = () => {
    if (!proposals) return;
    const proposal = proposals[currentProposalIndex];
    const diffs = diffFromProposal(data, baseline);
    if (diffs.length > 0) {
      const ok = window.confirm(
        `${diffs.length} 件の変更がありますが、新しい提案で上書きしますか？`,
      );
      if (!ok) return;
    }
    updateData(applyProposal(proposal));
    showToast('提案を適用しました');
  };

  const handleDiscardProposal = () => {
    updateData({ baseProposal: null });
    showToast('提案ベースを破棄しました');
  };

  const handleRevertField = (field: keyof NonNullable<SpecData['baseProposal']>) => {
    if (!baseline) return;
    updateData({ [field]: baseline[field] } as Partial<SpecData>);
  };

  const fabricType = useMemo(() => {
    const fabric = specJson.parameters.body_fabric.options?.find((opt) => opt.value === data.bodyFabric);
    return fabric?.type || 'pu';
  }, [data.bodyFabric]);

  const textureOptions = useMemo(() => {
    return specJson.parameters.texture.options_by_fabric_type?.[fabricType] ?? [];
  }, [fabricType]);

  useEffect(() => {
    if (data.texture && !textureOptions.find((o) => o.value === data.texture)) {
      updateData({ texture: '' });
    }
  }, [fabricType, textureOptions, data.texture, updateData]);

  /**
   * Layer 6 UX fix: when the user lands on Step2 after picking a sample
   * (Route A), the form has only headShape / brandName / bodyColor / lining
   * seeded — the remaining 6 fields are blank and there's no obvious next
   * action. Auto-fire generateProposals so the user sees 5 proposal cards and
   * can apply one with a single click.
   *
   * - Route B / C / undefined are unaffected (Route B already has full data
   *   from the source draft; Route C is intentionally blank).
   * - autoGeneratedRef prevents React strict-mode double-execution from
   *   re-firing after a manual `generateProposals` click.
   * - Empty deps to keep "first mount only" semantics.
   */
  useEffect(() => {
    if (autoGeneratedRef.current) return;
    if (
      data.originRoute === 'A' &&
      proposals === null &&
      data.headShape &&
      data.position
    ) {
      autoGeneratedRef.current = true;
      generateProposals();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const ngWarnings = useMemo(
    () => evaluateNgRules(data, specJson).map((v) => v.message),
    [data],
  );

  const canProceed =
    !!data.bodyFabric && !!data.lining && !!data.closure && !!data.embroidery && !!data.bodyColor && !!data.hardwareFinish;

  const fieldLabel = (text: string, fieldKey: keyof NonNullable<SpecData['baseProposal']>) => (
    <div className="flex items-center justify-between mb-1">
      <label className="block text-sm font-medium text-gray-700">{text}</label>
      <BaselineBadge
        baseline={baseline}
        fieldKey={fieldKey}
        currentValue={data[fieldKey] ?? ''}
        onRevert={() => handleRevertField(fieldKey)}
      />
    </div>
  );

  return (
    <div className="space-y-8 animate-fade-in fade-in pb-12">
      <ToastView />
      {isPositionMissing ? (
        <PositionMissingBanner onStepChange={onStepChange} />
      ) : (
        showGuide && (
          <GuideBanner data={data} draftLookup={draftLookup} onClose={() => setShowGuide(false)} />
        )
      )}
      {/* AI Proposal Section */}
      <div className="bg-gradient-to-r from-indigo-50 to-blue-50 p-6 rounded-xl border border-indigo-100 flex flex-col">
        <div className="flex items-center justify-between flex-wrap gap-2">
          <div>
            <h3 className="text-lg font-bold text-indigo-900 flex items-center gap-2">
              <SparklesIcon className="w-5 h-5 text-indigo-600" />
              AI組み合わせ提案
            </h3>
            <p className="text-sm text-indigo-700 mt-1">
              {SHAPE_LABELS_SHORT_JA[data.headShape]} × {POSITION_LABELS_JA[data.position]} の推奨パターンを提案します
            </p>
          </div>
          <div className="flex gap-2">
            {baseline && (
              <button
                onClick={handleDiscardProposal}
                className="inline-flex items-center gap-1 bg-white border border-gray-300 text-gray-700 hover:bg-gray-50 font-medium py-2 px-4 rounded shadow-sm"
              >
                <XCircleIcon className="w-4 h-4" /> 提案ベースを破棄
              </button>
            )}
            <button
              onClick={generateProposals}
              className="bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-2 px-6 rounded shadow transition-colors shrink-0"
            >
              提案を見る
            </button>
          </div>
        </div>

        {proposals && proposals.length > 0 && (
          <ProposalDeck
            proposals={proposals}
            currentIndex={currentProposalIndex}
            setCurrentIndex={setCurrentProposalIndex}
            onApply={handleApplyProposal}
            onRegenerate={regenerateProposals}
            getProposalWarnings={getProposalWarnings}
          />
        )}
      </div>

      {ngWarnings.length > 0 && (
        <div className="bg-red-50 border-l-4 border-red-500 p-4 rounded shadow-sm" role="alert">
          <div className="flex">
            <div className="flex-shrink-0">
              <ExclamationTriangleIcon className="h-5 w-5 text-red-500" aria-hidden="true" />
            </div>
            <div className="ml-3">
              <h3 className="text-sm font-medium text-red-800">仕様の見直しを推奨します</h3>
              <div className="mt-2 text-sm text-red-700">
                <ul className="list-disc pl-5 space-y-1">
                  {ngWarnings.map((warning, idx) => (
                    <li key={idx}>{warning}</li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-6">
        <div className="space-y-4">
          <h4 className="font-bold text-gray-800 border-b pb-2">■ 生地・素材</h4>
          <div>
            {fieldLabel('本体生地', 'bodyFabric')}
            <select
              className="w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 p-2 border"
              value={data.bodyFabric}
              onChange={(e) => updateData({ bodyFabric: e.target.value })}
            >
              <option value="">選択してください</option>
              {specJson.parameters.body_fabric.options?.map((o) => (
                <option key={o.value} value={o.value}>{o.label}</option>
              ))}
            </select>
          </div>
          <div>
            {fieldLabel('テクスチャー', 'texture')}
            <select
              className="w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 p-2 border"
              value={data.texture}
              onChange={(e) => updateData({ texture: e.target.value })}
            >
              <option value="">選択してください</option>
              {textureOptions.map((o) => (
                <option key={o.value} value={o.value}>{o.label}</option>
              ))}
            </select>
          </div>
          <div>
            {fieldLabel('裏地', 'lining')}
            <select
              className="w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 p-2 border"
              value={data.lining}
              onChange={(e) => updateData({ lining: e.target.value })}
            >
              <option value="">選択してください</option>
              {specJson.parameters.lining.options?.map((o) => (
                <option key={o.value} value={o.value}>{o.label}</option>
              ))}
            </select>
          </div>
          <div>
            {fieldLabel('パイピング', 'piping')}
            <select
              className="w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 p-2 border"
              value={data.piping}
              onChange={(e) => updateData({ piping: e.target.value })}
            >
              <option value="">選択してください</option>
              {specJson.parameters.piping.options?.map((o) => (
                <option key={o.value} value={o.value}>{o.label}</option>
              ))}
            </select>
          </div>
        </div>

        <div className="space-y-4">
          <h4 className="font-bold text-gray-800 border-b pb-2">■ 開閉・留め具</h4>
          <div>
            {fieldLabel('開閉・留め具方式', 'closure')}
            <select
              className="w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 p-2 border"
              value={data.closure}
              onChange={(e) => updateData({ closure: e.target.value })}
            >
              <option value="">選択してください</option>
              {specJson.parameters.closure.options?.map((o) => (
                <option key={o.value} value={o.value}>{o.label}</option>
              ))}
            </select>
          </div>
        </div>

        <div className="space-y-4">
          <h4 className="font-bold text-gray-800 border-b pb-2">■ 刺繍・装飾</h4>
          <div>
            {fieldLabel('主刺繍技法', 'embroidery')}
            <select
              className="w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 p-2 border"
              value={data.embroidery}
              onChange={(e) => updateData({ embroidery: e.target.value })}
            >
              <option value="">選択してください</option>
              {specJson.parameters.embroidery.options?.map((o) => (
                <option key={o.value} value={o.value}>{o.label}</option>
              ))}
            </select>
          </div>
        </div>

        <div className="space-y-4">
          <h4 className="font-bold text-gray-800 border-b pb-2">■ カラー指示</h4>
          <div>
            {fieldLabel('本体カラー', 'bodyColor')}
            <div className="relative">
              <select
                className="w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 p-2 border pl-10"
                value={data.bodyColor}
                onChange={(e) => updateData({ bodyColor: e.target.value })}
              >
                <option value="">選択してください</option>
                {specJson.parameters.body_color.options?.map((o) => (
                  <option key={o.value} value={o.value}>{o.label}</option>
                ))}
              </select>
              {data.bodyColor && COLOR_HEX_MAP[data.bodyColor] && (
                <span
                  className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 rounded-full border border-gray-300 shadow-sm"
                  style={{ backgroundColor: COLOR_HEX_MAP[data.bodyColor] }}
                ></span>
              )}
            </div>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">カラーコード</label>
            <input
              type="text"
              className="w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 p-2 border"
              value={data.colorCode}
              onChange={(e) => updateData({ colorCode: e.target.value })}
            />
          </div>

          <div className="grid grid-cols-2 gap-2">
            {(['A', 'B', 'C', 'D'] as const).map((label) => (
              <div key={label}>
                <label className="block text-xs text-gray-500">部位{label}</label>
                <input
                  type="text"
                  className="w-full border p-1 text-sm rounded"
                  value={data.fabricParts?.find((p) => p.id === label || p.label === label)?.colorName || ''}
                  onChange={(e) => {
                    const parts = [...(data.fabricParts || [])];
                    const idx = parts.findIndex((p) => p.id === label || p.label === label);
                    if (idx >= 0) parts[idx] = { ...parts[idx], colorName: e.target.value };
                    else
                      parts.push({
                        id: label,
                        label,
                        usage: '',
                        material: '',
                        partNumber: '',
                        quantity: '',
                        colorName: e.target.value,
                        colorSwatch: '#ccc',
                        threadNumber: '',
                      });
                    updateData({ fabricParts: parts });
                  }}
                />
              </div>
            ))}
          </div>

          <div>
            {fieldLabel('金具仕上げ', 'hardwareFinish')}
            <select
              className="w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 p-2 border"
              value={data.hardwareFinish}
              onChange={(e) => updateData({ hardwareFinish: e.target.value })}
            >
              <option value="">選択してください</option>
              {specJson.parameters.hardware_finish.options?.map((o) => (
                <option key={o.value} value={o.value}>{o.label}</option>
              ))}
            </select>
          </div>
        </div>
      </div>

      <div className="pt-6 border-t flex justify-between mt-8">
        <button
          onClick={onBack}
          className="bg-white border text-gray-700 hover:bg-gray-50 font-bold py-3 px-8 rounded-lg shadow-sm transition-colors"
        >
          ← 戻る
        </button>
        <button
          onClick={onNext}
          disabled={!canProceed}
          className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 px-8 rounded-lg shadow disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          STEP3へ進む →
        </button>
      </div>
    </div>
  );
}
