import { Font } from '@react-pdf/renderer';

/**
 * Registers Noto Sans JP (Regular + Bold) once for the entire PDF subsystem.
 *
 * Loads the BUSINESS_CHARSET-only subset WOFFs (~450 KB per weight) under
 * `/public/fonts/`, generated by `scripts/subset-fonts.ts` from the full
 * @fontsource/noto-sans-jp WOFFs. The full WOFFs are 1.4 MB each and balloon
 * @react-pdf/renderer end-to-end render time to ~10 s; the subsets cut that to
 * ~1-2 s. See docs/layer2-pdf-perf-decisions.md.
 *
 * If postinstall failed (subset files missing), the registration call below
 * silently no-ops at render time and @react-pdf/renderer falls back to its
 * built-in Helvetica (Latin only) — visually obvious, fix with
 * `npm run download:fonts && npm run subset-fonts`.
 *
 * Idempotent: importing this module multiple times only registers once thanks
 * to a module-level guard.
 */
let registered = false;

export const FONT_FAMILY = 'NotoSansJP';

export function ensureFontsRegistered(): void {
  if (registered) return;
  registered = true;
  Font.register({
    family: FONT_FAMILY,
    fonts: [
      { src: '/fonts/NotoSansJP-Regular-subset.woff', fontWeight: 'normal' },
      { src: '/fonts/NotoSansJP-Bold-subset.woff', fontWeight: 'bold' },
    ],
  });
  // Disable react-pdf's hyphenation, which mangles Japanese.
  Font.registerHyphenationCallback((word) => [word]);
}
